<a href="https://colab.research.google.com/github/Abdallah22s/Project-1/blob/main/00_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Start

In [ ]:
import torch

In [ ]:
# Scaler
scaler = torch.tensor(6)
scaler, scaler.ndim

(tensor(6), 0)

In [ ]:
# how to create a vector fo tensors
vector = torch.tensor([1, 2, 3])
vector, vector.ndim

(tensor([1, 2, 3]), 1)

In [12]:
# how to identify the shape of a tensor
vector.shape, scaler.shape

(torch.Size([3]), torch.Size([]))

In [15]:
# matrix
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
matrix, matrix.ndim, matrix.shape

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 2,
 torch.Size([2, 3]))

In [17]:
d3_tensor = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]])
d3_tensor, d3_tensor.ndim, d3_tensor.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9],
          [10, 11, 12]]]),
 3,
 torch.Size([1, 4, 3]))

In [18]:
# crate a random tensor
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.ndim, random_tensor.shape

(tensor([[0.3463, 0.8740, 0.4530, 0.7353],
         [0.8181, 0.3459, 0.9893, 0.6981],
         [0.1575, 0.6448, 0.8552, 0.3334]]),
 2,
 torch.Size([3, 4]))

In [19]:
random_tensor.dtype

torch.float32

In [20]:
x_tensor = torch.tensor([223, 223, 3])
x_tensor.ndim

1

In [ ]:
# zeros
zero_tensor = torch.zeros(size=(2, 2, 8))
zero_tensor, zero_tensor.ndim, zero_tensor.shape, zero_tensor.dtype

(tensor([[[0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0.]]]),
 3,
 torch.Size([2, 2, 8]),
 torch.float32)

In [22]:
# ones
ones_tensor = torch.ones(size=(2, 2, 8))
ones_tensor, ones_tensor.ndim, ones_tensor.shape, ones_tensor.dtype

(tensor([[[1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1.]]]),
 3,
 torch.Size([2, 2, 8]),
 torch.float32)

In [23]:
# arange
arange_tensor = torch.arange(start=0, end=10, step=1)
arange_tensor, arange_tensor.ndim, arange_tensor.shape, arange_tensor.dtype

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 1, torch.Size([10]), torch.int64)